name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: psychic-surf-420214 # TODO: update Google Cloud project id
  SERVICE: ${{ secrets.GCR_SERVICE_NAME }} # TODO: update Cloud Run service name
  REGION: europe-west4 # TODO: update Cloud Run service region

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:  
    
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          
      - uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          registry: gcr.io
          project_id: ${{ env.PROJECT_ID }}
          image_name: backend
          image_tag: latest,v1
          dockerfile: ./DBBetterAdminAPI/Dockerfile
          context: ./DBBetterAdminAPI

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
